name: build

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip3 install -U setuptools pytest
          pip3 install -e .

      - name: Test with pytest
        run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip3 install -U setuptools build

      - name: Build
        run: python3 -m build --wheel

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: zmkx
          path: dist/*.whl

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: zmkx
          path: dist

      - name: Publish release
        uses: svenstaro/upload-release-action@v2
        with:
          file: dist/*.whl
          file_glob: true
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true

  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: zmkx
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
